export enum DecisionType {
  CLAIMANT_IN_FAVOUR_OF_DEFENDANT = 'CLAIMANT_IN_FAVOUR_OF_DEFENDANT',
  CLAIMANT = 'CLAIMANT',
  DEFENDANT = 'DEFENDANT',
  COURT = 'COURT',
  NOT_APPLICABLE_IS_BUSINESS = 'NOT_APPLICABLE_IS_BUSINESS'
}
