nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.5.0.cjs

packageExtensions:

  "@azure/core-rest-pipeline@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "@babel/core@*":
    peerDependencies:
      "@babel/core": "^7.0.0"
      "supports-color": "^7.1.0"
  "@babel/helper-module-transforms@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "@babel/helpers@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "@babel/traverse@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "@codeceptjs/configure@*":
    peerDependencies:
      "bufferutil": "^4.0.1"
      "supports-color": "^7.1.0"
      "typescript": "^3.9.8"
      "utf-8-validate": "^5.0.2"
  "@hmcts/cmc-draft-store-middleware@*":
    peerDependencies:
      "request": "^2.88.2"
      "supports-color": "^7.1.0"
  "@hmcts/draft-store-client@*":
    peerDependencies:
      "request": "^2.88.2"
      "supports-color": "^7.1.0"
  "@hmcts/info-provider@*":
    peerDependencies:
      "request": "^2.88.2"
      "supports-color": "^7.1.0"
  "@hmcts/nodejs-healthcheck@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "@hmcts/os-places-client@*":
    peerDependencies:
      "request": "^2.88.2"
  "@hmcts/requestretry@*":
    peerDependencies:
      "request": "^2.88.2"
  "@wdio/config@*":
    peerDependencies:
      "typescript": "^3.9.8"
  "@wdio/repl@*":
    peerDependencies:
      "typescript": "^3.9.8"
  "@wdio/utils@*":
    peerDependencies:
      "typescript": "^3.9.8"
  "agent-base@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "agentkeepalive@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "anymatch@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "applicationinsights@*":
    peerDependencies:
      "@opentelemetry/api": "^1.0.1"
      "diagnostic-channel": "^1.0.1"
      "debug": "^2.3.3"
      "supports-color": "^7.1.0"
  "axios@*":
    peerDependencies:
      "debug": "^2.3.3"
  "body-parser@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "braces@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "cacache@*":
    peerDependencies:
      "bluebird": "^3.5.0"
  "chokidar@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "chrome-launcher@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "cmc-citizen-frontend@*":
    peerDependencies:
      "@babel/core": "^7.0.0"
      "@opentelemetry/api": "^1.0.1"
      "acorn": "^5.0.0"
      "applicationinsights-native-metrics": "*"
      "bluebird": "^3.5.0"
      "bufferutil": "^4.0.1"
      "canvas": "^2.5.0"
      "chokidar": "3.5.3"
      "debug": "^2.3.3"
      "diagnostic-channel": "^1.0.1"
      "encoding": "^0.1.0"
      "mocha": "^10.2.0"
      "mocha-parallel-tests": "^2.3.0"
      "moment": "2.19.1"
      "request": "^2.88.2"
      "sinon": "^9.2.4"
      "supports-color": "^7.1.0"
      "tslint": "^5.20.1"
      "typescript": "^3.9.8"
      "utf-8-validate": "^5.0.2"
  "codacy-coverage@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "request": "^2.88.2"
      "supports-color": "^7.1.0"
  "codeceptjs@*":
    peerDependencies:
      "bufferutil": "^4.0.1"
      "debug": "^2.3.3"
      "mocha": "^10.2.0"
      "supports-color": "^7.1.0"
      "typescript": "^3.9.8"
      "utf-8-validate": "^5.0.2"
  "codecov@*":
    peerDependencies:
      "encoding": "^0.1.0"
      "supports-color": "^7.1.0"
  "devtools@*":
    peerDependencies:
      "bufferutil": "^4.0.1"
      "supports-color": "^7.1.0"
      "typescript": "^3.9.8"
      "utf-8-validate": "^5.0.2"
  "eslint@*":
    peerDependencies:
      "acorn": "^5.0.0"
      "supports-color": "^7.1.0"
  "espree@*":
    peerDependencies:
      "acorn": "^5.0.0"
  "expand-brackets@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "express@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "extract-zip@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "extglob@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "finalhandler@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "findup-sync@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "fsevents@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "glob-watcher@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "gulp-cli@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "gulp-nodemon@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "gulp-livereload@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "gulp@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "http-proxy-agent@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "https-proxy-agent@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "istanbul-lib-instrument@*":
    peerDependencies:
      "@babel/core": "^7.0.0"
      "acorn": "^5.0.0"
      "supports-color": "^7.1.0"
  "istanbul-lib-source-maps@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "jacoco-parse@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "jsdom@*":
    peerDependencies:
      "bufferutil": "^4.0.1"
      "supports-color": "^7.1.0"
      "utf-8-validate": "^5.0.2"
  "liftoff@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "lighthouse-logger@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "make-fetch-happen@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "matchdep@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "micromatch@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "mocha-junit-reporter@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "mocha-multi@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "mocha-parallel-tests@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "mocha@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "nan@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "nanomatch@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "nock@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "node-gyp@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "nodemon@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "nyc@*":
    peerDependencies:
      "@babel/core": "^7.0.0"
      "acorn": "^5.0.0"
      "supports-color": "^7.1.0"
  "pa11y@*":
    peerDependencies:
      "bufferutil": "^4.0.1"
      "supports-color": "^7.1.0"
      "utf-8-validate": "^5.0.2"
  "puppeteer-core@*":
    peerDependencies:
      "bufferutil": "^4.0.1"
      "supports-color": "^7.1.0"
      "utf-8-validate": "^5.0.2"
  "puppeteer@*":
    peerDependencies:
      "bufferutil": "^4.0.1"
      "supports-color": "^7.1.0"
      "utf-8-validate": "^5.0.2"
  "readdirp@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "sass-lint@*":
    peerDependencies:
      "acorn": "^5.0.0"
      "supports-color": "^7.1.0"
  "sass@*":
    peerDependencies:
      "bluebird": "^3.5.0"
      "supports-color": "^7.1.0"
  "send@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "serve-static@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "socks-proxy-agent@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "sonarqube-scanner@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "snapdragon@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "superagent@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "supertest@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "teeny-request@*":
    peerDependencies:
      "encoding": "^0.1.0"
      "supports-color": "^7.1.0"
  "tiny-lr@*":
    peerDependencies:
      "supports-color": "^7.1.0"
  "tslint-config-standard@*":
    peerDependencies:
      "tslint": "^5.20.1"
      "typescript": "^3.9.8"
  "webdriver@*":
    peerDependencies:
      "typescript": "^3.9.8"
  "webdriverio@*":
    peerDependencies:
      "bufferutil": "^4.0.1"
      "supports-color": "^7.1.0"
      "typescript": "^3.9.8"
      "utf-8-validate": "^5.0.2"

