version: '2.1'

services:
    citizen-integration-tests:
      image: hmcts/cmc-citizen-integration-tests:${CITIZEN_INTEGRATION_TESTS_VERSION:-latest}
      command: test:integration --grep '@citizen($$| )'
      environment:
        - WEB_DRIVER_HOST=remote-webdriver
        - CITIZEN_APP_URL=${TEST_URL}
        - http_proxy
        - https_proxy
        - no_proxy=remote-webdriver
        - IDAM_URL
        - OAUTH2_CLIENT_SECRET
        - CLAIM_STORE_URL
        - HEALTHCHECK_CITIZEN=true
      volumes:
        - ./functional-output:/usr/src/app/output
    remote-webdriver:
      image: selenium/standalone-chrome:3.8.1

