version: '2.1'

services:
    citizen-integration-tests:
      image: hmctspublic.azurecr.io/cmc/citizen-integration-tests:${CITIZEN_INTEGRATION_TESTS_VERSION:-latest}
      command: test:integration --grep @citizen
      environment:
        - WEB_DRIVER_HOST=remote-webdriver
        - CITIZEN_APP_URL=https://cmc-citizen-frontend-pr-2308.service.core-compute-preview.internal
        - CLAIM_STORE_URL=http://claim-store-cmc-citizen-frontend-pr-2308.service.core-compute-preview.internal
        - IDAM_URL
        - http_proxy=http://proxyout.reform.hmcts.net:8080
        - https_proxy=http://proxyout.reform.hmcts.net:8080
        - no_proxy=remote-webdriver
        - OAUTH_CLIENT_SECRET
        - HEALTHCHECK_CITIZEN=true
        - FEATURE_ADMISSIONS
        - FEATURE_MEDIATION
        - FEATURE_DIRECTIONS_QUESTIONNAIRE
        - FEATURE_TESTING_SUPPORT
        - SMOKE_TEST_CITIZEN_USERNAME
        - SMOKE_TEST_USER_PASSWORD
        - FEATURE_INVERSION_OF_CONTROL
      volumes:
        - ./functional-output:/usr/src/app/output
    remote-webdriver:
      image: selenium/standalone-chrome:3.8.1
