version: '2.1'

services:
    citizen-integration-tests:
      image: hmcts/cmc-citizen-integration-tests:${CITIZEN_INTEGRATION_TESTS_VERSION:-latest}
      command: test:integration --grep '^(?!.*@admissions)(?!.*@citizen-smoke-test)'
      environment:
        - WEB_DRIVER_HOST=remote-webdriver
        - CITIZEN_APP_URL=${TEST_URL}
        - http_proxy=http://proxyout.reform.hmcts.net:8080
        - https_proxy=http://proxyout.reform.hmcts.net:8080
        - no_proxy=remote-webdriver
        - IDAM_URL
        - OAUTH_CLIENT_SECRET
        - CLAIM_STORE_URL
        - HEALTHCHECK_CITIZEN=true
        - FEATURE_TESTING_SUPPORT
        - FEATURE_NEW_FEATURES_CONSENT
        - FEATURE_ADMISSIONS
        - FEATURE_FINE_PRINT
        - FEATURE_RETURN_ERROR_TO_USER
        - FEATURE_MOCK_PAY
      volumes:
        - ./functional-output:/usr/src/app/output
    remote-webdriver:
      image: selenium/standalone-chrome:3.8.1
