"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const routablePath_1 = require("shared/router/routablePath");
class Paths {
}
exports.Paths = Paths;
Paths.taskListPage = new routablePath_1.RoutablePath('/claim/task-list');
Paths.resolvingThisDisputerPage = new routablePath_1.RoutablePath('/claim/resolving-this-dispute');
Paths.completingClaimPage = new routablePath_1.RoutablePath('/claim/completing-claim');
Paths.claimantIndividualDetailsPage = new routablePath_1.RoutablePath('/claim/claimant-individual-details');
Paths.claimantCompanyDetailsPage = new routablePath_1.RoutablePath('/claim/claimant-company-details');
Paths.claimantSoleTraderOrSelfEmployedDetailsPage = new routablePath_1.RoutablePath('/claim/claimant-sole-trader-details');
Paths.claimantOrganisationDetailsPage = new routablePath_1.RoutablePath('/claim/claimant-organisation-details');
Paths.defendantIndividualDetailsPage = new routablePath_1.RoutablePath('/claim/defendant-individual-details');
Paths.defendantCompanyDetailsPage = new routablePath_1.RoutablePath('/claim/defendant-company-details');
Paths.defendantSoleTraderOrSelfEmployedDetailsPage = new routablePath_1.RoutablePath('/claim/defendant-sole-trader-details');
Paths.defendantOrganisationDetailsPage = new routablePath_1.RoutablePath('/claim/defendant-organisation-details');
Paths.claimantDateOfBirthPage = new routablePath_1.RoutablePath('/claim/claimant-dob');
Paths.claimantPhonePage = new routablePath_1.RoutablePath('/claim/claimant-phone');
Paths.defendantEmailPage = new routablePath_1.RoutablePath('/claim/defendant-email');
Paths.defendantPhonePage = new routablePath_1.RoutablePath('/claim/defendant-mobile');
Paths.amountPage = new routablePath_1.RoutablePath('/claim/amount');
Paths.interestPage = new routablePath_1.RoutablePath('/claim/interest');
Paths.interestTypePage = new routablePath_1.RoutablePath('/claim/interest-type');
Paths.interestRatePage = new routablePath_1.RoutablePath('/claim/interest-rate');
Paths.interestDatePage = new routablePath_1.RoutablePath('/claim/interest-date');
Paths.interestStartDatePage = new routablePath_1.RoutablePath('/claim/interest-start-date');
Paths.interestEndDatePage = new routablePath_1.RoutablePath('/claim/interest-end-date');
Paths.interestTotalPage = new routablePath_1.RoutablePath('/claim/interest-total');
Paths.interestContinueClaimingPage = new routablePath_1.RoutablePath('/claim/interest-continue-claiming');
Paths.interestHowMuchPage = new routablePath_1.RoutablePath('/claim/interest-how-much');
Paths.totalPage = new routablePath_1.RoutablePath('/claim/total');
Paths.reasonPage = new routablePath_1.RoutablePath('/claim/reason');
Paths.timelinePage = new routablePath_1.RoutablePath('/claim/timeline');
Paths.evidencePage = new routablePath_1.RoutablePath('/claim/evidence');
Paths.checkAndSendPage = new routablePath_1.RoutablePath('/claim/check-and-send');
Paths.startPaymentReceiver = new routablePath_1.RoutablePath('/claim/pay');
Paths.finishPaymentReceiver = new routablePath_1.RoutablePath('/claim/pay/:externalId/receiver');
Paths.confirmationPage = new routablePath_1.RoutablePath('/claim/:externalId/confirmation');
Paths.receiptReceiver = new routablePath_1.RoutablePath('/claim/:externalId/receipt');
Paths.claimantPartyTypeSelectionPage = new routablePath_1.RoutablePath('/claim/claimant-party-type-selection');
Paths.defendantPartyTypeSelectionPage = new routablePath_1.RoutablePath('/claim/defendant-party-type-selection');
Paths.incompleteSubmissionPage = new routablePath_1.RoutablePath('/claim/incomplete-submission');
Paths.sealedClaimPdfReceiver = new routablePath_1.RoutablePath('/claim/:externalId/sealed-claim');
Paths.newFeaturesConsentPage = new routablePath_1.RoutablePath('/claim/new-features-consent');
Paths.initiatePaymentController = new routablePath_1.RoutablePath('/claim/initiate-payment');
Paths.finishPaymentController = new routablePath_1.RoutablePath('/claim/:externalId/finish-payment');
Paths.documentPage = new routablePath_1.RoutablePath('/claim/:externalId/document/:documentURI');
class ErrorPaths {
}
exports.ErrorPaths = ErrorPaths;
ErrorPaths.amountExceededPage = new routablePath_1.RoutablePath('/eligibility/not-eligible?reason=claim-value-over-10000');
