export enum ClaimStatus {
  ELIGIBLE_FOR_CCJ,
  CCJ_REQUESTED,
  OFFER_SUBMITTED,
  OFFER_ACCEPTED,
  OFFER_REJECTED,
  OFFER_SETTLEMENT_REACHED,
  MORE_TIME_REQUESTED,
  CLAIM_REJECTED,
  NO_RESPONSE
}
