export enum ClaimState {
  CREATE,
  OPEN,
  CLOSED,
  SETTLED,
  READY_FOR_DIRECTIONS,
  STAYED,
  ORDER_FOR_JUDGE_REVIEW,
  ORDER_FOR_LA_REVIEW,
  ORDER_DRAWN,
  TRANSFERRED,
  APPROVED,
  READY_FOR_TRANSFER,
  RECONSIDERATION_REQUESTED,
  REFERRED_MEDIATION,
  AWAITING_CITIZEN_PAYMENT,
  JUDGMENT_REQUESTED
}
