export enum ClaimStatus {
  NO_RESPONSE,
  MORE_TIME_REQUESTED,
  ELIGIBLE_FOR_CCJ,
  CCJ_REQUESTED,
  RESPONSE_SUBMITTED,
  OFFER_SUBMITTED,
  OFFER_ACCEPTED,
  OFFER_REJECTED,
  OFFER_SETTLEMENT_REACHED
}
