"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const dependants_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/dependants");
const education_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/education");
const employers_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/employers");
const employment_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/employment");
const on_tax_payments_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/on-tax-payments");
const residence_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/residence");
const self_employment_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/self-employment");
const start_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/start");
const bankAccounts_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/bankAccounts");
const other_dependants_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/other-dependants");
const unemployment_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/unemployment");
const debts_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/debts");
const courtOrders_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/courtOrders");
const monthlyIncome_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/monthlyIncome");
const monthlyExpenses_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/monthlyExpenses");
const explanation_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/explanation");
const disability_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/disability");
const partner_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/partner");
const carer_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/carer");
const partnerAge_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/partnerAge");
const partnerPension_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/partnerPension");
const partnerDisability_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/partnerDisability");
const partnerSevereDisability_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/partnerSevereDisability");
const severeDisability_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/severeDisability");
const priorityDebts_1 = require("integration-test/tests/citizen/defence/pages/statement-of-means/priorityDebts");
const startPage = new start_1.StartPage();
const bankAccountsPage = new bankAccounts_1.BankAccountsPage();
const disabilityPage = new disability_1.DisabilityPage();
const severeDisabilityPage = new severeDisability_1.SevereDisabilityPage();
const residencePage = new residence_1.ResidencePage();
const cohabitingPage = new partner_1.PartnerPage();
const partnerAgePage = new partnerAge_1.PartnerAgePage();
const partnerPensionPage = new partnerPension_1.PartnerPensionPage();
const partnerDisabilityPage = new partnerDisability_1.PartnerDisabilityPage();
const partnerSevereDisabilityPage = new partnerSevereDisability_1.PartnerSevereDisabilityPage();
const dependantsPage = new dependants_1.DependantsPage();
const educationPage = new education_1.EducationPage();
const otherDependantsPage = new other_dependants_1.OtherDependantsPage();
const carerPage = new carer_1.CarerPage();
const employmentPage = new employment_1.EmploymentPage();
const employersPage = new employers_1.EmployersPage();
const selfEmploymentPage = new self_employment_1.SelfEmploymentPage();
const onTaxPaymentsPage = new on_tax_payments_1.OnTaxPaymentsPage();
const unemploymentPage = new unemployment_1.UnemploymentPage();
const incomePage = new monthlyIncome_1.MonthlyIncomePage();
const expensesPage = new monthlyExpenses_1.MonthlyExpensesPage();
const debtsPage = new debts_1.DebtsPage();
const priorityDebtsPage = new priorityDebts_1.PriorityDebtsPage();
const courtOrdersPage = new courtOrders_1.CourtOrdersPage();
const explanationPage = new explanation_1.ExplanationPage();
class StatementOfMeansSteps {
    fillStatementOfMeansWithMinimalDataSet(amount) {
        startPage.clickContinue();
        bankAccountsPage.enterBankAccount('Current account', false, 1000);
        bankAccountsPage.clickContinue();
        disabilityPage.selectNoOption();
        residencePage.selectOwnHome();
        residencePage.clickContinue();
        cohabitingPage.selectNoOption();
        dependantsPage.selectNotDeclared();
        dependantsPage.clickContinue();
        otherDependantsPage.selectNotDeclared();
        otherDependantsPage.clickContinue();
        carerPage.selectNoOption();
        employmentPage.selectNotDeclared();
        employmentPage.clickContinue();
        unemploymentPage.selectRetired();
        unemploymentPage.clickContinue();
        courtOrdersPage.selectNotDeclared();
        courtOrdersPage.clickContinue();
        priorityDebtsPage.clickContinue();
        debtsPage.selectNotDeclared();
        debtsPage.clickContinue();
        expensesPage.fillOutSomeFields();
        expensesPage.clickContinue();
        incomePage.fillOutSomeFields(amount);
        incomePage.clickContinue();
        explanationPage.enterExplanation('I cannot pay immediately');
        explanationPage.clickContinue();
    }
    fillStatementOfMeansWithFullDataSet() {
        startPage.clickContinue();
        bankAccountsPage.enterBankAccount('Saving account', true, 10000);
        bankAccountsPage.clickContinue();
        disabilityPage.selectYesOption();
        severeDisabilityPage.selectYesOption();
        residencePage.selectOther('Special home');
        residencePage.clickContinue();
        cohabitingPage.selectYesOption();
        partnerAgePage.selectYesOption();
        partnerPensionPage.selectYesOption();
        partnerDisabilityPage.selectYesOption();
        partnerSevereDisabilityPage.selectYesOption();
        dependantsPage.selectDeclared();
        dependantsPage.enterNumberOfChildren(1, 2, 3);
        dependantsPage.clickContinue();
        educationPage.enterNumberOfChildren(3);
        educationPage.clickContinue();
        // dependant disability page is skipped
        otherDependantsPage.selectDeclared();
        otherDependantsPage.enterNumberOfPeople(5, 'Colleagues');
        otherDependantsPage.clickContinue();
        // carer page is skipped
        employmentPage.selectDeclared();
        employmentPage.tickEmployed();
        employmentPage.tickSelfEmployed();
        employmentPage.clickContinue();
        employersPage.enterDetails('Happy Dogs and Cats', 'Junior Accountant');
        employersPage.clickContinue();
        selfEmploymentPage.enterDetails('CEO', 1000);
        selfEmploymentPage.clickContinue();
        onTaxPaymentsPage.selectDeclared();
        onTaxPaymentsPage.enterDetails(100, 'Various taxes');
        onTaxPaymentsPage.clickContinue();
        courtOrdersPage.selectDeclared();
        courtOrdersPage.enterCourtOrder('000MC001', 100, 10);
        courtOrdersPage.clickContinue();
        priorityDebtsPage.declareMortgage(500);
        priorityDebtsPage.declareMaintenance(200);
        priorityDebtsPage.clickContinue();
        debtsPage.selectDeclared();
        debtsPage.enterDebt('Wife\'s debt', 100, 10);
        debtsPage.clickContinue();
        expensesPage.fillOutSomeFields();
        expensesPage.clickContinue();
        incomePage.fillOutSomeFields();
        incomePage.clickContinue();
        explanationPage.enterExplanation('I cannot pay immediately');
        explanationPage.clickContinue();
    }
}
exports.StatementOfMeansSteps = StatementOfMeansSteps;
