export enum FullAdmissionStates {
  FULL_ADMISSION = 'full-admission',
  FA_PAY_IMMEDIATELY = 'fa-pay-immediately',
  FA_PAY_IMMEDIATELY_PAST_DEADLINE = 'fa-pay-immediately-past-deadline',
  FA_CCJ_PAST_PAYMENT_DEADLINE_BY_ADMISSION = 'fa-ccj-past-payment-deadline-by-admission',
  FA_SETTLED_PAID_IN_FULL = 'fa-settled-paid-in-full',
  FA_PAY_BY_SPECIFIED_DATE = 'fa-pay-by-specified-date',
  FA_PAY_IN_INSTALMENTS = 'fa-pay-in-instalments',
  FA_PAY_BY_SPECIFIED_DATE_REFERRED_TO_JUDGE = 'fa-pay-by-specified-date-referred-to-judge',
  FA_PAY_IN_INSTALMENTS_REFERRED_TO_JUDGE = 'fa-pay-in-instalments-referred-to-judge',

  FA_CCJ_PAY_BY_SET_DATE_BY_ADMISSION = 'fa-ccj-pay-by-set-date-by-admission',
  FA_CCJ_PAY_IN_INSTALMENTS_BY_ADMISSION = 'fa-ccj-pay-in-instalments-by-admission',
  FA_PAY_BY_SET_DATE_CLAIMANT_OFFER_ACCEPTED_BY_ADMISSION = 'fa-pay-by-set-date-claimant-offer-accepted-by-admission',
  FA_PAY_BY_SET_DATE_PAST_COUNTER_SIGNATURE_DEADLINE_BY_ADMISSION = 'fa-pay-by-set-date-past-counter-signature-deadline-by-admission',
  FA_PAY_BY_SET_DATE_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_ADMISSION = 'fa-pay-by-set-date-defendant-rejected-claimant-offer-by-admission',
  FA_CCJ_PAY_BY_SET_DATE_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_ADMISSION = 'fa-ccj-pay-by-set-date-defendant-rejected-claimant-offer-by-admission',
  FA_CCJ_PAY_BY_SET_DATE_PAST_COUNTER_SIGNATURE_DEADLINE_BY_ADMISSION = 'fa-ccj-pay-by-set-date-past-counter-signature-deadline-by-admission',
  FA_PAY_BY_SET_DATE_SETTLED_THROUGH_ADMISSION = 'fa-pay-by-set-date-settled-through-admission',
  FA_PAY_BY_SET_DATE_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_ADMISSION = 'fa-pay-by-set-date-past-payment-deadline-settled-through-admission',
  FA_CCJ_PAY_BY_SET_DATE_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_ADMISSION = 'fa-ccj-pay-by-set-date-past-payment-deadline-settled-through-admission',

  FA_PAY_IN_INSTALMENTS_CLAIMANT_OFFER_ACCEPTED_BY_ADMISSION = 'fa-pay-in-instalments-claimant-offer-accepted-by-admission',
  FA_PAY_IN_INSTALMENTS_PAST_COUNTER_SIGNATURE_DEADLINE_BY_ADMISSION = 'fa-pay-in-instalments-past-counter-signature-deadline-by-admission',
  FA_PAY_IN_INSTALMENTS_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_ADMISSION = 'fa-pay-in-instalments-defendant-rejected-claimant-offer-by-admission',
  FA_CCJ_PAY_IN_INSTALMENTS_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_ADMISSION = 'fa-ccj-pay-in-instalments-defendant-rejected-claimant-offer-by-admission',
  FA_CCJ_PAY_IN_INSTALMENTS_PAST_COUNTER_SIGNATURE_DEADLINE_BY_ADMISSION = 'fa-ccj-pay-in-instalments-past-counter-signature-deadline-by-admission',
  FA_PAY_IN_INSTALMENTS_SETTLED_THROUGH_ADMISSION = 'fa-pay-in-instalments-settled-through-admission',
  FA_PAY_IN_INSTALMENTS_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_ADMISSION = 'fa-pay-in-instalments-past-payment-deadline-settled-through-admission',
  FA_CCJ_PAY_IN_INSTALMENTS_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_ADMISSION = 'fa-ccj-pay-in-instalments-past-payment-deadline-settled-through-admission',

  FA_PAY_BY_SET_DATE_CLAIMANT_OFFER_ACCEPTED_BY_DETERMINATION = 'fa-pay-by-set-date-claimant-offer-accepted-by-determination',
  FA_CCJ_PAY_BY_SET_DATE_BY_DETERMINATION = 'fa-ccj-pay-by-set-date-by-determination',
  FA_PAY_BY_SET_DATE_PAST_COUNTER_SIGNATURE_DEADLINE_BY_DETERMINATION = 'fa-pay-by-set-date-past-counter-signature-deadline-by-determination',
  FA_PAY_BY_SET_DATE_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_DETERMINATION = 'fa-pay-by-set-date-defendant-rejected-claimant-offer-by-determination',
  FA_CCJ_PAY_BY_SET_DATE_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_DETERMINATION = 'fa-ccj-pay-by-set-date-defendant-rejected-claimant-offer-by-determination',
  FA_CCJ_PAY_BY_SET_DATE_PAST_COUNTER_SIGNATURE_DEADLINE_BY_DETERMINATION = 'fa-ccj-pay-by-set-date-past-counter-signature-deadline-by-determination',
  FA_PAY_BY_SET_DATE_SETTLED_THROUGH_DETERMINATION = 'fa-pay-by-set-date-settled-through-determination',
  FA_PAY_BY_SET_DATE_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_DETERMINATION = 'fa-pay-by-set-date-past-payment-deadline-settled-through-determination',
  FA_CCJ_PAY_BY_SET_DATE_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_DETERMINATION = 'fa-ccj-pay-by-set-date-past-payment-deadline-settled-through-determination',

  FA_PAY_IN_INSTALMENTS_CLAIMANT_OFFER_ACCEPTED_BY_DETERMINATION = 'fa-pay-in-instalments-claimant-offer-accepted-by-determination',
  FA_CCJ_PAY_IN_INSTALMENTS_BY_DETERMINATION = 'fa-ccj-pay-in-instalments-by-determination',
  FA_PAY_IN_INSTALMENTS_PAST_COUNTER_SIGNATURE_DEADLINE_BY_DETERMINATION = 'fa-pay-in-instalments-past-counter-signature-deadline-by-determination',
  FA_PAY_IN_INSTALMENTS_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_DETERMINATION = 'fa-pay-in-instalments-defendant-rejected-claimant-offer-by-determination',
  FA_CCJ_PAY_IN_INSTALMENTS_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_DETERMINATION = 'fa-ccj-pay-in-instalments-defendant-rejected-claimant-offer-by-determination',
  FA_CCJ_PAY_IN_INSTALMENTS_PAST_COUNTER_SIGNATURE_DEADLINE_BY_DETERMINATION = 'fa-ccj-pay-in-instalments-past-counter-signature-deadline-by-determination',
  FA_PAY_IN_INSTALMENTS_SETTLED_THROUGH_DETERMINATION = 'fa-pay-in-instalments-settled-through-determination',
  FA_PAY_IN_INSTALMENTS_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_DETERMINATION = 'fa-pay-in-instalments-past-payment-deadline-settled-through-determination',
  FA_CCJ_PAY_IN_INSTALMENTS_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_DETERMINATION = 'fa-ccj-pay-in-instalments-past-payment-deadline-settled-through-determination'
}
