export enum PartAdmissionStates {
  PART_ADMISSION = 'part-admission',
  PA_PAY_IMMEDIATELY_WITH_MEDIATION = 'pa-pay-immediately-with-mediation',
  PA_PAY_IMMEDIATELY_WITHOUT_MEDIATION = 'pa-pay-immediately-without-mediation',
  PA_PAY_IMMEDIATELY_ACCEPTED_WITH_MEDIATION = 'pa-pay-immediately-accepted-with-mediation',
  PA_PAY_IMMEDIATELY_ACCEPTED_WITHOUT_MEDIATION = 'pa-pay-immediately-accepted-without-mediation',
  PA_PAY_IMMEDIATELY_REJECTED_WITH_MEDIATION_CLAIMANT_WITHOUT_MEDIATION = 'pa-pay-immediately-rejected-with-mediation-claimant-without-mediation',
  PA_PAY_IMMEDIATELY_REJECTED_WITH_MEDIATION_CLAIMANT_WITH_MEDIATION = 'pa-pay-immediately-rejected-with-mediation-claimant-with-mediation',
  PA_PAY_IMMEDIATELY_REJECTED_WITHOUT_MEDIATION = 'pa-pay-immediately-rejected-without-mediation',
  PA_PAY_IMMEDIATELY_WITH_MEDIATION_PAST_DEADLINE = 'pa-pay-immediately-with-mediation-past-deadline',
  PA_PAY_IMMEDIATELY_WITHOUT_MEDIATION_PAST_DEADLINE = 'pa-pay-immediately-without-mediation-past-deadline',
  PA_CCJ_PAST_PAYMENT_DEADLINE_WITH_MEDIATION_BY_ADMISSION = 'pa-ccj-past-payment-deadline-with-mediation-by-admission',
  PA_CCJ_PAST_PAYMENT_DEADLINE_WITHOUT_MEDIATION_BY_ADMISSION = 'pa-ccj-past-payment-deadline-without-mediation-by-admission',

  PA_PAY_BY_SET_DATE_WITH_MEDIATION = 'pa-pay-by-set-date-with-mediation',
  PA_PAY_BY_SET_DATE_WITHOUT_MEDIATION = 'pa-pay-by-set-date-without-mediation',
  PA_PAY_BY_SET_DATE_REJECTED_WITH_MEDIATION_CLAIMANT_WITHOUT_MEDIATION = 'pa-pay-by-set-date-rejected-with-mediation-claimant-without-mediation',
  PA_PAY_BY_SET_DATE_REJECTED_WITH_MEDIATION_CLAIMANT_WITH_MEDIATION = 'pa-pay-by-set-date-rejected-with-mediation-claimant-with-mediation',
  PA_PAY_BY_SET_DATE_REJECTED_WITHOUT_MEDIATION = 'pa-pay-by-set-date-rejected-without-mediation',

  PA_PAY_IN_INSTALMENTS_WITH_MEDIATION = 'pa-pay-in-instalments-with-mediation',
  PA_PAY_IN_INSTALMENTS_WITHOUT_MEDIATION = 'pa-pay-in-instalments-without-mediation',
  PA_PAY_IN_INSTALMENTS_REJECTED_WITH_MEDIATION_CLAIMANT_WITHOUT_MEDIATION = 'pa-pay-in-instalments-rejected-with-mediation-claimant-without-mediation',
  PA_PAY_IN_INSTALMENTS_REJECTED_WITH_MEDIATION_CLAIMANT_WITH_MEDIATION = 'pa-pay-in-instalments-rejected-with-mediation-claimant-with-mediation',
  PA_PAY_IN_INSTALMENTS_REJECTED_WITHOUT_MEDIATION = 'pa-pay-in-instalments-rejected-without-mediation',

  PA_PAY_BY_SPECIFIED_DATE = 'pa-pay-by-specified-date',
  PA_PAY_IN_INSTALMENTS = 'pa-pay-in-instalments',
  PA_PAY_BY_SPECIFIED_DATE_REFERRED_TO_JUDGE = 'pa-pay-by-specified-date-referred-to-judge',
  PA_PAY_IN_INSTALMENTS_REFERRED_TO_JUDGE = 'pa-pay-in-instalments-referred-to-judge',

  PA_CCJ_PAY_BY_SET_DATE_BY_ADMISSION = 'pa-ccj-pay-by-set-date-by-admission',
  PA_CCJ_PAY_IN_INSTALMENTS_BY_ADMISSION = 'pa-ccj-pay-in-instalments-by-admission',
  PA_PAY_BY_SET_DATE_CLAIMANT_OFFER_ACCEPTED_BY_ADMISSION = 'pa-pay-by-set-date-claimant-offer-accepted-by-admission',
  PA_PAY_BY_SET_DATE_PAST_COUNTER_SIGNATURE_DEADLINE_BY_ADMISSION = 'pa-pay-by-set-date-past-counter-signature-deadline-by-admission',
  PA_PAY_BY_SET_DATE_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_ADMISSION = 'pa-pay-by-set-date-defendant-rejected-claimant-offer-by-admission',
  PA_CCJ_PAY_BY_SET_DATE_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_ADMISSION = 'pa-ccj-pay-by-set-date-defendant-rejected-claimant-offer-by-admission',
  PA_CCJ_PAY_BY_SET_DATE_PAST_COUNTER_SIGNATURE_DEADLINE_BY_ADMISSION = 'pa-ccj-pay-by-set-date-past-counter-signature-deadline-by-admission',
  PA_PAY_BY_SET_DATE_SETTLED_THROUGH_ADMISSION = 'pa-pay-by-set-date-settled-through-admission',
  PA_PAY_BY_SET_DATE_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_ADMISSION = 'pa-pay-by-set-date-past-payment-deadline-settled-through-admission',
  PA_CCJ_PAY_BY_SET_DATE_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_ADMISSION = 'pa-ccj-pay-by-set-date-past-payment-deadline-settled-through-admission',

  PA_PAY_IN_INSTALMENTS_CLAIMANT_OFFER_ACCEPTED_BY_ADMISSION = 'pa-pay-in-instalments-claimant-offer-accepted-by-admission',
  PA_PAY_IN_INSTALMENTS_PAST_COUNTER_SIGNATURE_DEADLINE_BY_ADMISSION = 'pa-pay-in-instalments-past-counter-signature-deadline-by-admission',
  PA_PAY_IN_INSTALMENTS_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_ADMISSION = 'pa-pay-in-instalments-defendant-rejected-claimant-offer-by-admission',
  PA_CCJ_PAY_IN_INSTALMENTS_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_ADMISSION = 'pa-ccj-pay-in-instalments-defendant-rejected-claimant-offer-by-admission',
  PA_CCJ_PAY_IN_INSTALMENTS_PAST_COUNTER_SIGNATURE_DEADLINE_BY_ADMISSION = 'pa-ccj-pay-in-instalments-past-counter-signature-deadline-by-admission',
  PA_PAY_IN_INSTALMENTS_SETTLED_THROUGH_ADMISSION = 'pa-pay-in-instalments-settled-through-admission',
  PA_PAY_IN_INSTALMENTS_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_ADMISSION = 'pa-pay-in-instalments-past-payment-deadline-settled-through-admission',
  PA_CCJ_PAY_IN_INSTALMENTS_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_ADMISSION = 'pa-ccj-pay-in-instalments-past-payment-deadline-settled-through-admission',

  PA_PAY_BY_SET_DATE_CLAIMANT_OFFER_ACCEPTED_BY_DETERMINATION = 'pa-pay-by-set-date-claimant-offer-accepted-by-determination',
  PA_CCJ_PAY_BY_SET_DATE_BY_DETERMINATION = 'pa-ccj-pay-by-set-date-by-determination',
  PA_PAY_BY_SET_DATE_PAST_COUNTER_SIGNATURE_DEADLINE_BY_DETERMINATION = 'pa-pay-by-set-date-past-counter-signature-deadline-by-determination',
  PA_PAY_BY_SET_DATE_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_DETERMINATION = 'pa-pay-by-set-date-defendant-rejected-claimant-offer-by-determination',
  PA_CCJ_PAY_BY_SET_DATE_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_DETERMINATION = 'pa-ccj-pay-by-set-date-defendant-rejected-claimant-offer-by-determination',
  PA_CCJ_PAY_BY_SET_DATE_PAST_COUNTER_SIGNATURE_DEADLINE_BY_DETERMINATION = 'pa-ccj-pay-by-set-date-past-counter-signature-deadline-by-determination',
  PA_PAY_BY_SET_DATE_SETTLED_THROUGH_DETERMINATION = 'pa-pay-by-set-date-settled-through-determination',
  PA_PAY_BY_SET_DATE_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_DETERMINATION = 'pa-pay-by-set-date-past-payment-deadline-settled-through-determination',
  PA_CCJ_PAY_BY_SET_DATE_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_DETERMINATION = 'pa-ccj-pay-by-set-date-past-payment-deadline-settled-through-determination',

  PA_PAY_IN_INSTALMENTS_CLAIMANT_OFFER_ACCEPTED_BY_DETERMINATION = 'pa-pay-in-instalments-claimant-offer-accepted-by-determination',
  PA_CCJ_PAY_IN_INSTALMENTS_BY_DETERMINATION = 'pa-ccj-pay-in-instalments-by-determination',
  PA_PAY_IN_INSTALMENTS_PAST_COUNTER_SIGNATURE_DEADLINE_BY_DETERMINATION = 'pa-pay-in-instalments-past-counter-signature-deadline-by-determination',
  PA_PAY_IN_INSTALMENTS_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_DETERMINATION = 'pa-pay-in-instalments-defendant-rejected-claimant-offer-by-determination',
  PA_CCJ_PAY_IN_INSTALMENTS_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_DETERMINATION = 'pa-ccj-pay-in-instalments-defendant-rejected-claimant-offer-by-determination',
  PA_CCJ_PAY_IN_INSTALMENTS_PAST_COUNTER_SIGNATURE_DEADLINE_BY_DETERMINATION = 'pa-ccj-pay-in-instalments-past-counter-signature-deadline-by-determination',
  PA_PAY_IN_INSTALMENTS_SETTLED_THROUGH_DETERMINATION = 'pa-pay-in-instalments-settled-through-determination',
  PA_PAY_IN_INSTALMENTS_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_DETERMINATION = 'pa-pay-in-instalments-past-payment-deadline-settled-through-determination',
  PA_CCJ_PAY_IN_INSTALMENTS_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_DETERMINATION = 'pa-ccj-pay-in-instalments-past-payment-deadline-settled-through-determination'

}
