export enum PartAdmissionStates {
  PART_ADMISSION = 'part-admission',
  PA_PAY_IMMEDIATELY_WITH_MEDIATION = 'pa-pay-immediately-with-mediation',
  PA_PAY_IMMEDIATELY_WITHOUT_MEDIATION = 'pa-pay-immediately-without-mediation',
  PA_PAY_IMMEDIATELY_ACCEPTED_WITH_MEDIATION = 'pa-pay-immediately-accepted-with-mediation',
  PA_PAY_IMMEDIATELY_ACCEPTED_WITHOUT_MEDIATION = 'pa-pay-immediately-accepted-without-mediation',
  PA_PAY_IMMEDIATELY_REJECTED_WITH_MEDIATION_CLAIMANT_WITHOUT_MEDIATION = 'pa-pay-immediately-rejected-with-mediation-claimant-without-mediation',
  PA_PAY_IMMEDIATELY_REJECTED_WITH_MEDIATION_CLAIMANT_WITH_MEDIATION = 'pa-pay-immediately-rejected-with-mediation-claimant-with-mediation',
  PA_PAY_IMMEDIATELY_REJECTED_WITHOUT_MEDIATION = 'pa-pay-immediately-rejected-without-mediation',
  PA_PAY_IMMEDIATELY_WITH_MEDIATION_PAST_DEADLINE = 'pa-pay-immediately-with-mediation-past-deadline',
  PA_PAY_IMMEDIATELY_WITHOUT_MEDIATION_PAST_DEADLINE = 'pa-pay-immediately-without-mediation-past-deadline',
  PA_CCJ_PAST_PAYMENT_DEADLINE_WITH_MEDIATION_BY_ADMISSION = 'pa-ccj-past-payment-deadline-with-mediation-by-admission',
  PA_CCJ_PAST_PAYMENT_DEADLINE_WITHOUT_MEDIATION_BY_ADMISSION = 'pa-ccj-past-payment-deadline-without-mediation-by-admission',

  PA_PAY_BY_SET_DATE_WITH_MEDIATION = 'pa-pay-by-set-date-with-mediation',
  PA_PAY_BY_SET_DATE_WITHOUT_MEDIATION = 'pa-pay-by-set-date-without-mediation',
  PA_PAY_BY_SET_DATE_ACCEPTED_WITH_MEDIATION = 'pa-pay-by-set-date-accepted-with-mediation',
  PA_PAY_BY_SET_DATE_ACCEPTED_WITHOUT_MEDIATION = 'pa-pay-by-set-date-accepted-without-mediation',
  PA_PAY_BY_SET_DATE_REJECTED_WITH_MEDIATION_CLAIMANT_WITHOUT_MEDIATION = 'pa-pay-by-set-date-rejected-with-mediation-claimant-without-mediation',
  PA_PAY_BY_SET_DATE_REJECTED_WITH_MEDIATION_CLAIMANT_WITH_MEDIATION = 'pa-pay-by-set-date-rejected-with-mediation-claimant-with-mediation',
  PA_PAY_BY_SET_DATE_REJECTED_WITHOUT_MEDIATION = 'pa-pay-by-set-date-rejected-without-mediation',

  PA_PAY_BY_INSTALMENTS_WITH_MEDIATION = 'pa-pay-by-installments-with-mediation',
  PA_PAY_BY_INSTALMENTS_WITHOUT_MEDIATION = 'pa-pay-by-installments-without-mediation',
  PA_PAY_BY_INSTALMENTS_ACCEPTED_WITH_MEDIATION = 'pa-pay-by-installments-accepted-with-mediation',
  PA_PAY_BY_INSTALMENTS_ACCEPTED_WITHOUT_MEDIATION = 'pa-pay-by-installments-accepted-without-mediation',
  PA_PAY_BY_INSTALMENTS_REJECTED_WITH_MEDIATION_CLAIMANT_WITHOUT_MEDIATION = 'pa-pay-by-installments-rejected-with-mediation-claimant-without-mediation',
  PA_PAY_BY_INSTALMENTS_REJECTED_WITH_MEDIATION_CLAIMANT_WITH_MEDIATION = 'pa-pay-by-installments-rejected-with-mediation-claimant-with-mediation',
  PA_PAY_BY_INSTALMENTS_REJECTED_WITHOUT_MEDIATION = 'pa-pay-by-installments-rejected-without-mediation',

  PA_SETTLED_PAID_IN_FULL = 'pa-settled-paid-in-full',
  PA_PAY_BY_SPECIFIED_DATE = 'pa-pay-by-specified-date',
  PA_PAY_BY_INSTALMENTS = 'pa-pay-by-instalments',
  PA_REFERRED_TO_JUDGE = 'pa-referred-to-judge',
  PA_CCJ_BY_ADMISSION = 'pa-ccj-by-admission',
  PA_CLAIMANT_OFFER_ACCEPTED_BY_ADMISSION = 'pa-claimant-offer-accepted-by-admission',
  PA_PAST_COUNTER_SIGNATURE_DEADLINE_BY_ADMISSION = 'pa-past-counter-signature-deadline-by-admission',
  PA_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_ADMISSION = 'pa-defendant-rejected-claimant-offer-by-admission',
  PA_CCJ_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_ADMISSION = 'pa-ccj-defendant-rejected-claimant-offer-by-admission',
  PA_CCJ_PAST_COUNTER_SIGNATURE_DEADLINE_BY_ADMISSION = 'pa-ccj-past-counter-signature-deadline-by-admission',
  PA_SETTLED_THROUGH_ADMISSION = 'pa-settled-through-admission',
  PA_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_ADMISSION = 'pa-past-payment-deadline-settled-through-admission',
  PA_CCJ_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_ADMISSION = 'pa-ccj-past-payment-deadline-settled-through-admission',
  PA_CLAIMANT_OFFER_ACCEPTED_BY_DETERMINATION = 'pa-claimant-offer-accepted-by-determination',
  PA_CCJ_BY_DETERMINATION = 'pa-ccj-by-determination',
  PA_PAST_COUNTER_SIGNATURE_DEADLINE_BY_DETERMINATION = 'pa-past-counter-signature-deadline-by-determination',
  PA_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_DETERMINATION = 'pa-defendant-rejected-claimant-offer-by-determination',
  PA_CCJ_DEFENDANT_REJECTED_CLAIMANT_OFFER_BY_DETERMINATION = 'pa-ccj-defendant-rejected-claimant-offer-by-determination',
  PA_CCJ_PAST_COUNTER_SIGNATURE_DEADLINE_BY_DETERMINATION = 'pa-ccj-past-counter-signature-deadline-by-determination',
  PA_SETTLED_THROUGH_DETERMINATION = 'pa-settled-through-determination',
  PA_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_DETERMINATION = 'pa-past-payment-deadline-settled-through-determination',
  PA_CCJ_PAST_PAYMENT_DEADLINE_SETTLED_THROUGH_DETERMINATION = 'pa-ccj-past-payment-deadline-settled-through-determination'
}
