vault_section = "preprod"
feature_fine_print = "true"
feature_full_admission = "true"
feature_partial_admission = "true"
feature_statement_of_means = "true"
feature_return_error_to_user = "true"
external_host_name = "moneyclaim.nonprod.platform.hmcts.net"

idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net"
fees_api_url = "https://preprod.fees-register.reform.hmcts.net:4411"
payments_api_url = "https://preprod.payments.reform.hmcts.net:4401"
capacity = "2"

fees_api_url = "http://fees-register-api-aat.service.core-compute-aat.internal"
payments_api_url = "http://payment-api-aat.service.core-compute-aat.internal"
