vault_section = "preprod"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
s2s_url = "https://preprod-s2s-api.reform.hmcts.net:3511"
authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net"
fees_api_url = "https://preprod.fees-register.reform.hmcts.net:4411"
payments_api_url = "https://preprod.payments.reform.hmcts.net:4401"
draft_store_api_url = "https://preproddraftstorelb.moneyclaim.reform.hmcts.net:4301"
