feature_fine_print = "true"
feature_new_features_consent = "true"
feature_admissions = "true"

idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net"
fees_api_url = "http://fees-register-api-aat.service.core-compute-aat.internal"
payments_api_url = "http://payment-api-aat.service.core-compute-aat.internal"
feature_paid_in_full = "true"
feature_testing_support = "true"
