idam_api_url = "https://prod-idamapi.reform.hmcts.net:3511"
authentication_web_url = "https://hmcts-access.service.gov.uk"
fees_api_url = "https://fees-register-api.platform.hmcts.net"
payments_api_url = "https://payment.platform.hmcts.net"
ga_tracking_id = "UA-97111056-2"
external_host_name = "www.moneyclaims.service.gov.uk"
feature_return_error_to_user = "false"
capacity = "2"
