feature_fine_print = "true"
feature_full_admission = "true"
feature_partial_admission = "true"
feature_statement_of_means = "true"
external_host_name = "moneyclaims.saat.platform.hmcts.net"

idam_api_url = "http://betaDevBccidamAppLB.reform.hmcts.net"
authentication_web_url = "https://idam-test.dev.ccidam.reform.hmcts.net"
fees_api_url = "http://fees-register-api-aat.service.core-compute-aat.internal"
payments_api_url = "http://payment-api-aat.service.core-compute-aat.internal"
capacity = "2"
