feature_fine_print = "true"
feature_admissions = "true"
external_host_name = "moneyclaims.saat.platform.hmcts.net"

idam_api_url = "http://betadevbccidamapplb.reform.hmcts.net"
authentication_web_url = "https://idam-test.dev.ccidam.reform.hmcts.net"
fees_api_url = "http://fees-register-api-saat.service.core-compute-saat.internal"
payments_api_url = "http://payment-api-saat.service.core-compute-saat.internal"
feature_testing_support = "true"
feature_new_features_consent = "true"
