feature_mock_pay = "true"
feature_fine_print = "true"
feature_new_features_consent = "true"
feature_return_error_to_user = "true"
external_host_name = "moneyclaims.sprod.platform.hmcts.net"

idam_api_url = "http://betaDevBccidamAppLB.reform.hmcts.net"
authentication_web_url = "https://idam-test.dev.ccidam.reform.hmcts.net"
fees_api_url = "http://fees-register-api-sprod.service.core-compute-sprod.internal"
payments_api_url = "http://payment-api-sprod.service.core-compute-sprod.internal"
capacity = "2"
feature_testing_support = "true"
