tags:
  - rpe-feature-toggle-api

rpe-feature-toggle-api:
  releaseNameOverride: ${SERVICE_NAME}-ftr-tgl-api
  registerDns: false
  importer:
    cron:
      enabled: false
    oneoff:
      command: /scripts/add-weighted-toggle.sh cmc_admissions 'CMC admissions' '1.0'
        ${ADMIN_USERNAME_TEST} ${ADMIN_PASSWORD_TEST} && /scripts/add-toggle.sh cmc_defence_reminders
        'CMC defence reminders' false ${ADMIN_USERNAME_TEST} ${ADMIN_PASSWORD_TEST}
      enabled: true
      permissions: cmc-new-features-consent-given
  java:
    image: hmcts.azurecr.io/hmcts/rpe-feature-toggle-api:latest
    releaseNameOverride: ${SERVICE_NAME}-ftr-tgl-api
    environment:
      FEATURES_DB_HOST: ${SERVICE_NAME}-ft-db
  postgresql:
    postgresqlDatabase: hmcts

nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 3000
  memoryRequests: 256Mi
  cpuRequests: 0.2
  memoryLimits: 512Mi
  cpuLimits: 1
  environment:
    IDAM_API_URL: https://preprod-idamapi.reform.hmcts.net:3511
    IDAM_URL: https://preprod-idamapi.reform.hmcts.net:3511
    IDAM_AUTHENTICATION_WEB_URL: https://idam.preprod.ccidam.reform.hmcts.net
    IDAM_S2S_AUTH: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    PAY_URL: http://payment-api-aat.service.core-compute-aat.internal
    FEES_URL: http://fees-register-api-aat.service.core-compute-aat.internal
    CLAIM_STORE_URL: http://cmc-claim-store-aat.service.core-compute-aat.internal
    DRAFT_STORE_URL: http://draft-store-service-aat.service.core-compute-aat.internal
    REFORM_TEAM: cmc
    REFORM_SERVICE_NAME: citizen-frontend
    REFORM_ENVIRONMENT: preview
    NODE_ENV: production
    UV_THREADPOOL_SIZE: 64
    GA_TRACKING_ID: UA-97111056-1
    SERVICE_SURVEY_URL: http://www.smartsurvey.co.uk/s/CMCMVPT1/
    FEEDBACK_SURVEY_URL: http://www.smartsurvey.co.uk/s/CMCMVPFB/
    REPORT_PROBLEM_SURVEY_URL: http://www.smartsurvey.co.uk/s/CMCMVPPB/
    FEATURE_TOGGLES_API_URL: http://${SERVICE_NAME}-ftr-tgl-api
    FEATURE_TESTING_SUPPORT: true
    FEATURE_NEW_FEATURES_CONSENT: true
    FEATURE_ADMISSIONS: true
    FEATURE_FINE_PRINT: true
    FEATURE_RETURN_ERROR_TO_USER: true
    FEATURE_MOCK_PAY: false
    FEATURE_MEDIATION: false
  keyVaults:
    cmc:
      resourceGroup: cmc
      secrets:
      - os-postcode-lookup-api-key
      - AppInsightsInstrumentationKey
      - citizen-oauth-client-secret
      - cmc-s2s-secret
      - citizen-draft-store-primary
      - citizen-draft-store-secondary
      - citizen-cookie-encryption-key
      - staff-email
