rpe-feature-toggle-api:
  releaseNameOverride: ${SERVICE_NAME}-ftr-tgl-api
  registerDns: false
  importer:
    cron:
      enabled: false
    oneoff:
      command: /scripts/add-weighted-toggle.sh cmc_admissions 'CMC admissions' '1.0'
        admin@example.com Password12 && /scripts/add-toggle.sh cmc_defence_reminders
        'CMC defence reminders' false admin@example.com Password12
      enabled: true
      permissions: cmc-new-features-consent-given
  java:
    releaseNameOverride: ${SERVICE_NAME}-ftr-tgl-api
    environment:
      FEATURES_DB_HOST: ${SERVICE_NAME}-ft-db
      ADMIN_USERNAME_TEST: admin@example.com
      ADMIN_PASSWORD_TEST: Password12
      EDITOR_USERNAME_TEST: editor@example.com
      EDITOR_PASSWORD_TEST: Password12
  postgresql:
    postgresqlDatabase: hmcts

nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 3000
  memoryRequests: 256Mi
  cpuRequests: 0.2
  memoryLimits: 512Mi
  cpuLimits: 1
  keyVault:
    'cmc':
      resourceGroup: 'cmc'
      secrets:
        - smoke-test-citizen-username
        - smoke-test-user-password
        - os-postcode-lookup-api-key
        - AppInsightsInstrumentationKey
        - citizen-oauth-client-secret
        - cmc-s2s-secret
        - citizen-draft-store-primary
        - citizen-draft-store-secondary
        - citizen-cookie-encryption-key
        - staff-email
  environment:    
    REFORM_TEAM: cmc
    REFORM_SERVICE_NAME: citizen-frontend
    REFORM_ENVIRONMENT: preview
    NODE_ENV: production
    UV_THREADPOOL_SIZE: 64
    GA_TRACKING_ID: UA-97111056-1
    SERVICE_SURVEY_URL: http://www.smartsurvey.co.uk/s/CMCMVPT1/
    FEEDBACK_SURVEY_URL: http://www.smartsurvey.co.uk/s/CMCMVPFB/
    REPORT_PROBLEM_SURVEY_URL: http://www.smartsurvey.co.uk/s/CMCMVPPB/
    FEATURE_TOGGLES_API_URL: http://${SERVICE_NAME}-ftr-tgl-api
    FEATURE_TESTING_SUPPORT: true
    FEATURE_NEW_FEATURES_CONSENT: true
    FEATURE_ADMISSIONS: true
    FEATURE_FINE_PRINT: true
    FEATURE_RETURN_ERROR_TO_USER: true
    FEATURE_MOCK_PAY: false
    FEATURE_MEDIATION: false
