on: push
name: yarn build, lint, and test
jobs:
  build-and-test:
    name: build and test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn install
      - run: yarn global add gulp-cli
      - run: gulp copy-files
      - run: yarn lint
      - run: yarn tests:a11y
