on: push
name: yarn build, lint, and test
jobs:
  build-and-test:
    name: build and test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - run: yarn install
      - run: yarn install --global gulp-cli
      - run: gulp copy-files
      - run: yarn lint
      - run: yarn test:action-a11y
      - run: yarn test
      - run: yarn test:action-coverage
