import I = CodeceptJS.I
import { createClaimData } from 'integration-test/data/test-data'
import { PartyType } from 'integration-test/data/party-type'
import { PaymentOption } from 'integration-test/data/payment-option'
import { DefenceType } from 'integration-test/data/defence-type'
import { Helper } from 'integration-test/tests/citizen/endToEnd/steps/helper'
import { DefenceSteps } from 'integration-test/tests/citizen/defence/steps/defence'
import { UserSteps } from 'integration-test/tests/citizen/home/steps/user'
import { ClaimantResponseSteps } from 'integration-test/tests/citizen/claimantResponse/steps/claimant-reponse'
import { DashboardPage } from 'integration-test/tests/citizen/dashboard/pages/dashboard'
import { ClaimantDashboardPage } from 'integration-test/tests/citizen/dashboard/pages/claimant'
import { ClaimantTaskListPage } from 'integration-test/tests/citizen/claimantResponse/pages/claimant-task-list'
import { ClaimantDefendantResponsePage } from 'integration-test/tests/citizen/claimantResponse/pages/claimant-defendant-response'
import { ClaimantSettleAdmittedPage } from 'integration-test/tests/citizen/claimantResponse/pages/claimant-settle-admitted'
import { ClaimantCheckAndSendPage } from 'integration-test/tests/citizen/claimantResponse/pages/claimant-check-and-send'
import { ClaimantConfirmation } from 'integration-test/tests/citizen/claimantResponse/pages/claimant-confirmation'
import { DirectionsQuestionnaireSteps } from 'integration-test/tests/citizen/directionsQuestionnaire/steps/directionsQuestionnaireSteps'
import { DefendantDashboardPage } from 'integration-test/tests/citizen/dashboard/pages/defendant'
import { ClaimantAcceptPaymentMethod } from 'integration-test/tests/citizen/claimantResponse/pages/claimant-accept-payment-method'
import { ClaimantChooseHowToProceed } from 'integration-test/tests/citizen/claimantResponse/pages/claimant-choose-how-to-proceed'
import { ClaimantSignSettlementAgreement } from 'integration-test/tests/citizen/claimantResponse/pages/claimant-sign-settlement-agreement'
import { DefendantSignSettlementAgreement } from 'integration-test/tests/citizen/defence/pages/defendant-sign-settlement-agreement'
import { DefendantSignSettlementAgreementConfirmation } from 'integration-test/tests/citizen/defence/pages/defendant-sign-settlement-agreement-confirmation'
import { DefendantPaidAnyMoneyPage } from 'integration-test/tests/citizen/ccj/pages/defendant-paid-any-money'
import { PaidAmountSummaryPage } from 'integration-test/tests/citizen/ccj/pages/paid-amount-summary'
import { ClaimantPaymentOptionPage } from 'integration-test/tests/citizen/claimantResponse/pages/claimant-payment-option'
import { ClaimantCourtOfferedInstalmentsPage } from 'integration-test/tests/citizen/claimantResponse/pages/claimant-court-offered-instalments'
import { DefendantSettlementAgreementRepaymentPlanSummary } from 'integration-test/tests/citizen/defence/pages/defendant-settlement-agreement-repayment-plan-summary'

const helperSteps: Helper = new Helper()
const defenceSteps: DefenceSteps = new DefenceSteps()
const userSteps: UserSteps = new UserSteps()
const claimantResponseSteps: ClaimantResponseSteps = new ClaimantResponseSteps()
const dashboardPage: DashboardPage = new DashboardPage()
const claimantDashboardPage: ClaimantDashboardPage = new ClaimantDashboardPage()
const claimantTaskListPage: ClaimantTaskListPage = new ClaimantTaskListPage()
const claimantDefendantResponsePage: ClaimantDefendantResponsePage = new ClaimantDefendantResponsePage()
const claimantSettleAdmittedPage: ClaimantSettleAdmittedPage = new ClaimantSettleAdmittedPage()
const claimantCheckAndSendPage: ClaimantCheckAndSendPage = new ClaimantCheckAndSendPage()
const claimantConfirmation: ClaimantConfirmation = new ClaimantConfirmation()
const directionsQuestionnaireSteps: DirectionsQuestionnaireSteps = new DirectionsQuestionnaireSteps()
const defendantDashboardPage: DefendantDashboardPage = new DefendantDashboardPage()
const claimantAcceptPaymentMethod: ClaimantAcceptPaymentMethod = new ClaimantAcceptPaymentMethod()
const claimantChooseHowToProceed: ClaimantChooseHowToProceed = new ClaimantChooseHowToProceed()
const claimantSignSettlementAgreement: ClaimantSignSettlementAgreement = new ClaimantSignSettlementAgreement()
const defendantSignSettlementAgreement: DefendantSignSettlementAgreement = new DefendantSignSettlementAgreement()
const defendantSignSettlementAgreementConfirmation: DefendantSignSettlementAgreementConfirmation = new DefendantSignSettlementAgreementConfirmation()
const defendantPaidAnyMoneyPage: DefendantPaidAnyMoneyPage = new DefendantPaidAnyMoneyPage()
const paidAmountSummaryPage: PaidAmountSummaryPage = new PaidAmountSummaryPage()
const claimantPaymentOptionPage: ClaimantPaymentOptionPage = new ClaimantPaymentOptionPage()
const claimantCourtOfferedInstalmentsPage: ClaimantCourtOfferedInstalmentsPage = new ClaimantCourtOfferedInstalmentsPage()
const defendantSettlementAgreementRepaymentPlanSummary: DefendantSettlementAgreementRepaymentPlanSummary = new DefendantSettlementAgreementRepaymentPlanSummary()

async function prepareClaim (I: I) {
  const claimantEmail: string = userSteps.getClaimantEmail()
  const defendantEmail: string = userSteps.getDefendantEmail()

  const claimData: ClaimData = createClaimData(PartyType.INDIVIDUAL, PartyType.INDIVIDUAL)
  const claimRef: string = await I.createClaim(claimData, claimantEmail)

  await helperSteps.enterPinNumber(claimRef, claimantEmail)
  helperSteps.linkClaimToDefendant(defendantEmail)
  helperSteps.startResponseFromDashboard(claimRef)

  return { data: claimData, claimRef: claimRef }
}

if (process.env.FEATURE_ADMISSIONS === 'true') {
  Feature('Partially admit the claim')

  Scenario('I can complete the journey when I partially admit the claim with payment already made @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentMade(PartyType.INDIVIDUAL)
  })

  Scenario('I can complete the journey when I partially admit the claim with immediate payment @nightly @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.IMMEDIATELY)
  })

  Scenario('I can complete the journey when I partially admit the claim with by set date payment @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.BY_SET_DATE)
  })

  Scenario('I can complete the journey when I partially admit the claim with instalments payment @nightly @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.INSTALMENTS)
  })

  Scenario('I can complete the journey when I partially admit the claim with immediate payment and claimant accept the payment @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.IMMEDIATELY)
    const claimantEmail: string = userSteps.getClaimantEmail()
    dashboardPage.logout()
    claimantResponseSteps.loginAsClaimant(claimantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    claimantDashboardPage.clickViewAndRespond()
    claimantTaskListPage.selectTaskViewDefendantResponse()
    claimantDefendantResponsePage.submit()
    claimantTaskListPage.selectTaskAcceptOrRejectSpecificAmount(10)
    claimantSettleAdmittedPage.selectAdmittedYes()
    claimantTaskListPage.selectTaskCheckandSubmitYourResponse()
    claimantCheckAndSendPage.verifyFactsForPartAdmitAcceptance()
    claimantCheckAndSendPage.submitNoDq()
    claimantConfirmation.verifyAcceptanceConfirmation()
    claimantConfirmation.clickGoToYourAccount()
  })

  Scenario('I can complete the journey when I partially admit the claim with immediate payment and claimant reject the payment @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.IMMEDIATELY)
    const claimantEmail: string = userSteps.getClaimantEmail()
    const defendantEmail: string = userSteps.getDefendantEmail()
    dashboardPage.logout()
    claimantResponseSteps.loginAsClaimant(claimantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    claimantDashboardPage.clickViewAndRespond()
    claimantTaskListPage.selectTaskViewDefendantResponse()
    claimantDefendantResponsePage.submit()
    claimantTaskListPage.selectTaskAcceptOrRejectSpecificAmount(10)
    claimantSettleAdmittedPage.selectAdmittedNo()
    claimantTaskListPage.selectTaskHearingRequirements()
    directionsQuestionnaireSteps.acceptDirectionsQuestionnaireNoJourneyAsClaimant()
    claimantTaskListPage.selectTaskCheckandSubmitYourResponse()
    claimantCheckAndSendPage.verifyFactsForPartAdmitRejection()
    claimantCheckAndSendPage.checkFactsTrueAndSubmit(DefenceType.PART_ADMISSION)
    claimantConfirmation.verifyRejectionConfirmation(DefenceType.PART_ADMISSION)
    claimantConfirmation.clickGoToYourAccount()
    dashboardPage.logout()
    defenceSteps.loginAsDefendant(defendantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    defendantDashboardPage.verifyPartAdmitRejectStatus(claimData.data.claimants[0].name, 10)
  })

  Scenario('I can complete the journey when I partially admit the claim with installments and claimant reject the payment @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.INSTALMENTS)
    const claimantEmail: string = userSteps.getClaimantEmail()
    const defendantEmail: string = userSteps.getDefendantEmail()
    dashboardPage.logout()
    claimantResponseSteps.loginAsClaimant(claimantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    claimantDashboardPage.clickViewAndRespond()
    claimantTaskListPage.selectTaskViewDefendantResponse()
    claimantDefendantResponsePage.submit()
    claimantDefendantResponsePage.submitHowTheyWantToPay()
    claimantTaskListPage.selectTaskAcceptOrRejectSpecificAmount(10)
    claimantSettleAdmittedPage.selectAdmittedNo()
    claimantTaskListPage.selectTaskHearingRequirements()
    directionsQuestionnaireSteps.acceptDirectionsQuestionnaireNoJourneyAsClaimant()
    claimantTaskListPage.selectTaskCheckandSubmitYourResponse()
    claimantCheckAndSendPage.verifyFactsForPartAdmitRejection()
    claimantCheckAndSendPage.checkFactsTrueAndSubmit(DefenceType.PART_ADMISSION)
    claimantConfirmation.verifyRejectionConfirmation(DefenceType.PART_ADMISSION)
    claimantConfirmation.clickGoToYourAccount()
    dashboardPage.logout()
    defenceSteps.loginAsDefendant(defendantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    defendantDashboardPage.verifyPartAdmitRejectStatus(claimData.data.claimants[0].name, 10)
  })

  Scenario('I can complete the journey when I partially admit the claim by set date and claimant reject the payment @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.BY_SET_DATE)
    const claimantEmail: string = userSteps.getClaimantEmail()
    const defendantEmail: string = userSteps.getDefendantEmail()
    dashboardPage.logout()
    claimantResponseSteps.loginAsClaimant(claimantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    claimantDashboardPage.clickViewAndRespond()
    claimantTaskListPage.selectTaskViewDefendantResponse()
    claimantDefendantResponsePage.submit()
    claimantDefendantResponsePage.submitHowTheyWantToPay()
    claimantTaskListPage.selectTaskAcceptOrRejectSpecificAmount(10)
    claimantSettleAdmittedPage.selectAdmittedNo()
    claimantTaskListPage.selectTaskHearingRequirements()
    directionsQuestionnaireSteps.acceptDirectionsQuestionnaireNoJourneyAsClaimant()
    claimantTaskListPage.selectTaskCheckandSubmitYourResponse()
    claimantCheckAndSendPage.verifyFactsForPartAdmitRejection()
    claimantCheckAndSendPage.checkFactsTrueAndSubmit(DefenceType.PART_ADMISSION)
    claimantConfirmation.verifyRejectionConfirmation(DefenceType.PART_ADMISSION)
    claimantConfirmation.clickGoToYourAccount()
    dashboardPage.logout()
    defenceSteps.loginAsDefendant(defendantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    defendantDashboardPage.verifyPartAdmitRejectStatus(claimData.data.claimants[0].name, 10)
  })

  Scenario('I can complete the journey when I partially admit the claim with installments and claimant accept the repayment plan with settlement agreement and defendant accept settlement agreement @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.INSTALMENTS)
    const claimantEmail: string = userSteps.getClaimantEmail()
    const defendantEmail: string = userSteps.getDefendantEmail()
    dashboardPage.logout()
    claimantResponseSteps.loginAsClaimant(claimantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    claimantDashboardPage.clickViewAndRespond()
    claimantTaskListPage.selectTaskViewDefendantResponse()
    claimantDefendantResponsePage.submit()
    claimantDefendantResponsePage.submitHowTheyWantToPay()
    claimantTaskListPage.selectTaskAcceptOrRejectSpecificAmount(10)
    claimantSettleAdmittedPage.selectAdmittedYes()
    claimantTaskListPage.selectTaskAcceptOrRejectTheirRepaymentPlan()
    claimantAcceptPaymentMethod.chooseYes()
    claimantTaskListPage.selectTaskChooseHowToFormaliseRepayment()
    claimantChooseHowToProceed.chooseSettlement()
    claimantTaskListPage.selectTaskSignASettlementAgreement()
    claimantSignSettlementAgreement.confirm()
    claimantTaskListPage.selectTaskCheckandSubmitYourResponse()
    claimantCheckAndSendPage.verifyFactsForPartAdmitAcceptance()
    claimantCheckAndSendPage.submitNoDq()
    claimantConfirmation.verifyAcceptanceSettlementConfirmation()
    claimantConfirmation.clickGoToYourAccount()
    dashboardPage.logout()
    defenceSteps.loginAsDefendant(defendantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    defendantDashboardPage.verifySettlementAggrement(claimData.data.claimants[0].name)
    defendantDashboardPage.clickViewTheRepaymentPlane()
    defendantSignSettlementAgreement.confirm()
    defendantSignSettlementAgreementConfirmation.verifyAcceptanceConfirmation()
  })

  Scenario('I can complete the journey when I partially admit the claim with installments and claimant accept the repayment plan with settlement agreement and defendant rejects settlement agreement @citizen @admissions', { retries: 1 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.INSTALMENTS)
    const claimantEmail: string = userSteps.getClaimantEmail()
    const defendantEmail: string = userSteps.getDefendantEmail()
    dashboardPage.logout()
    claimantResponseSteps.loginAsClaimant(claimantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    claimantDashboardPage.clickViewAndRespond()
    claimantTaskListPage.selectTaskViewDefendantResponse()
    claimantDefendantResponsePage.submit()
    claimantDefendantResponsePage.submitHowTheyWantToPay()
    claimantTaskListPage.selectTaskAcceptOrRejectSpecificAmount(10)
    claimantSettleAdmittedPage.selectAdmittedYes()
    claimantTaskListPage.selectTaskAcceptOrRejectTheirRepaymentPlan()
    claimantAcceptPaymentMethod.chooseYes()
    claimantTaskListPage.selectTaskChooseHowToFormaliseRepayment()
    claimantChooseHowToProceed.chooseSettlement()
    claimantTaskListPage.selectTaskSignASettlementAgreement()
    claimantSignSettlementAgreement.confirm()
    claimantTaskListPage.selectTaskCheckandSubmitYourResponse()
    claimantCheckAndSendPage.verifyFactsForSettlement()
    claimantCheckAndSendPage.submitNoDq()
    claimantConfirmation.verifyAcceptanceSettlementConfirmation()
    claimantConfirmation.clickGoToYourAccount()
    dashboardPage.logout()
    defenceSteps.loginAsDefendant(defendantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    defendantDashboardPage.verifySettlementAggrement(claimData.data.claimants[0].name)
    defendantDashboardPage.clickViewTheRepaymentPlane()
    defendantSignSettlementAgreement.reject()
    defendantSignSettlementAgreementConfirmation.verifyRejectionConfirmation()
  })

  Scenario('I can complete the journey when I partially admit the claim with installments and claimant accept the repayment plan with CCJ @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.INSTALMENTS)
    const claimantEmail: string = userSteps.getClaimantEmail()
    const defendantEmail: string = userSteps.getDefendantEmail()
    dashboardPage.logout()
    claimantResponseSteps.loginAsClaimant(claimantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    claimantDashboardPage.clickViewAndRespond()
    claimantTaskListPage.selectTaskViewDefendantResponse()
    claimantDefendantResponsePage.submit()
    claimantDefendantResponsePage.submitHowTheyWantToPay()
    claimantTaskListPage.selectTaskAcceptOrRejectSpecificAmount(10)
    claimantSettleAdmittedPage.selectAdmittedYes()
    claimantTaskListPage.selectTaskAcceptOrRejectTheirRepaymentPlan()
    claimantAcceptPaymentMethod.chooseYes()
    claimantTaskListPage.selectTaskChooseHowToFormaliseRepayment()
    claimantChooseHowToProceed.chooseRequestCcj()
    claimantTaskListPage.selectTaskRequestCountyCourtJudgment()
    defendantPaidAnyMoneyPage.notPaidSome()
    defendantPaidAnyMoneyPage.submit()
    paidAmountSummaryPage.checkAmountsNotPaidSome(10)
    paidAmountSummaryPage.continue()
    claimantTaskListPage.selectTaskCheckandSubmitYourResponse()
    claimantCheckAndSendPage.verifyFactsForCCJ()
    claimantCheckAndSendPage.submitNoDq()
    claimantConfirmation.verifyCCJConfirmation()
    claimantConfirmation.clickGoToYourAccount()
    dashboardPage.logout()
    defenceSteps.loginAsDefendant(defendantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    defendantDashboardPage.verifyCCJRequestStatus(claimData.data.claimants[0].name)
  })

  Scenario('I can complete the journey when I partially admit the claim with installments and claimant reject the repayment plan and suggest immediately but accept court repayment plan with settlement agreement and defendant accept settlement agreement @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.INSTALMENTS)
    const claimantEmail: string = userSteps.getClaimantEmail()
    const defendantEmail: string = userSteps.getDefendantEmail()
    dashboardPage.logout()
    claimantResponseSteps.loginAsClaimant(claimantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    claimantDashboardPage.clickViewAndRespond()
    claimantTaskListPage.selectTaskViewDefendantResponse()
    claimantDefendantResponsePage.submit()
    claimantDefendantResponsePage.submitHowTheyWantToPay()
    claimantTaskListPage.selectTaskAcceptOrRejectSpecificAmount(10)
    claimantSettleAdmittedPage.selectAdmittedYes()
    claimantTaskListPage.selectTaskAcceptOrRejectTheirRepaymentPlan()
    claimantAcceptPaymentMethod.chooseNo()
    claimantTaskListPage.selectProposeAnAlternativeRepaymentPlan()
    claimantPaymentOptionPage.chooseImmediately()
    claimantCourtOfferedInstalmentsPage.accept()
    claimantTaskListPage.selectTaskChooseHowToFormaliseRepayment()
    claimantChooseHowToProceed.chooseSettlement()
    claimantTaskListPage.selectTaskSignASettlementAgreement()
    claimantSignSettlementAgreement.confirm()
    claimantTaskListPage.selectTaskCheckandSubmitYourResponse()
    claimantCheckAndSendPage.verifyFactsForPartAdmitAcceptance()
    claimantCheckAndSendPage.submitNoDq()
    claimantConfirmation.verifyAcceptanceSettlementConfirmation()
    claimantConfirmation.clickGoToYourAccount()
    dashboardPage.logout()
    defenceSteps.loginAsDefendant(defendantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    defendantDashboardPage.verifyCourtDeterminationRepaymentPlan(claimData.data.claimants[0].name)
    defendantDashboardPage.clickViewTheRepaymentPlane()
    defendantSettlementAgreementRepaymentPlanSummary.verifyRepaymentPlanSummary()
    defendantSettlementAgreementRepaymentPlanSummary.respondeToSettlementAgreement()
    defendantSignSettlementAgreement.confirm()
    defendantSignSettlementAgreementConfirmation.verifyAcceptanceConfirmation()
  })

  Scenario('I can complete the journey when I partially admit the claim by set date and claimant accept the repayment plan with settlement agreement and defendant accept settlement agreement @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.INDIVIDUAL, PaymentOption.BY_SET_DATE)
    const claimantEmail: string = userSteps.getClaimantEmail()
    const defendantEmail: string = userSteps.getDefendantEmail()
    dashboardPage.logout()
    claimantResponseSteps.loginAsClaimant(claimantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    claimantDashboardPage.clickViewAndRespond()
    claimantTaskListPage.selectTaskViewDefendantResponse()
    claimantDefendantResponsePage.submit()
    claimantDefendantResponsePage.submitHowTheyWantToPay()
    claimantTaskListPage.selectTaskAcceptOrRejectSpecificAmount(10)
    claimantSettleAdmittedPage.selectAdmittedYes()
    claimantTaskListPage.selectTaskAcceptOrRejectTheirRepaymentPlan()
    claimantAcceptPaymentMethod.chooseYes()
    claimantTaskListPage.selectTaskChooseHowToFormaliseRepayment()
    claimantChooseHowToProceed.chooseSettlement()
    claimantTaskListPage.selectTaskSignASettlementAgreement()
    claimantSignSettlementAgreement.confirm()
    claimantTaskListPage.selectTaskCheckandSubmitYourResponse()
    claimantCheckAndSendPage.verifyFactsForPartAdmitAcceptance()
    claimantCheckAndSendPage.submitNoDq()
    claimantConfirmation.verifyAcceptanceSettlementConfirmation()
    claimantConfirmation.clickGoToYourAccount()
    dashboardPage.logout()
    defenceSteps.loginAsDefendant(defendantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    defendantDashboardPage.verifySettlementAggrement(claimData.data.claimants[0].name)
    defendantDashboardPage.clickViewTheRepaymentPlane()
    defendantSignSettlementAgreement.confirm()
    defendantSignSettlementAgreementConfirmation.verifyAcceptanceConfirmation()
  })

  Scenario('I as a SOLE TRADER can complete the journey when I partially admit the claim with immediate payment and claimant accept the payment @citizen @admissions', { retries: 3 }, async (I: I) => {
    const claimData = await prepareClaim(I)
    defenceSteps.makePartialAdmission(claimData.data.defendants[0])
    defenceSteps.partialPaymentNotMade(PartyType.SOLE_TRADER, PaymentOption.IMMEDIATELY)
    const claimantEmail: string = userSteps.getClaimantEmail()
    dashboardPage.logout()
    claimantResponseSteps.loginAsClaimant(claimantEmail)
    dashboardPage.selectClaim(claimData.claimRef)
    claimantDashboardPage.clickViewAndRespond()
    claimantTaskListPage.selectTaskViewDefendantResponse()
    claimantDefendantResponsePage.submit()
    claimantTaskListPage.selectTaskAcceptOrRejectSpecificAmount(10)
    claimantSettleAdmittedPage.selectAdmittedYes()
    claimantTaskListPage.selectTaskCheckandSubmitYourResponse()
    claimantCheckAndSendPage.verifyFactsForPartAdmitAcceptance()
    claimantCheckAndSendPage.submitNoDq()
    claimantConfirmation.verifyAcceptanceConfirmation()
    claimantConfirmation.clickGoToYourAccount()
  })

}
